name: testing cypress   
on: [push]
jobs:
  build-flask:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set_up_python 
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: install_dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python init_db.py
        
    - name: run_flask
      run: |
        export FLASK_APP=hello.py

        flask run

  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: sleep 20 | npm run cypress:run