name: testing cypress   
on: [push]
jobs:
  build-flask:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set_up_python 
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python init_db.py
        
    - name: run flask
      run: |
        export FLASK_APP=hello.py
        flask run

     - name: cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run cypress:run